name: gotest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: "1.19.x"

    - run: sudo apt update && sudo apt install --yes zfsutils-linux
    
    - run: sudo go test ./...
